<?php
define('LANGUAGE', 'de');
define('SLOGAN', 'Datei-Hosting einfach gemacht');
define('UPLOADMULTIPLEFILES', 'Dateien ablegen oder hier klicken');
define('UPLOADSINGLEFILE', 'Datei ablegen oder hier klicken');
define('JAVASCRIPTWARNING', 'JavaScript ist nicht aktiviert. Bitte aktivieren sie es um alle Funktionen freizuschalten.');
define('VPNWARNING', 'Wir haben ein VPN erkannt. Ein VPN zu benutzen könnte Funktionen kaputt machen.');
define('RECENTS', 'Letzte Dateien');
define('ERRORS', 'Fehler');
define('UPLOADFAILED', 'Hochladen fehlgeschlagen');
define('NOFILEUPLOADED', 'Keine Datei hochgeladen');
define('FILETOOLARGE', 'Datei zu groß');
define('SERVERERROR', 'Server Fehler');
define('PARTIALLYUPLOADED', 'Teilweise Hochgeladen');
define('UPLOADCANCELLED', 'Hochladen abgebrochen');
define('FOOTERDESCRIPTION', 'Starfiles ist ein gratis Datei-Hosting Service der Benutzern erlaubt Dateien einfach zu verwahren und zu verschicken.');
define('HELPTEXT', 'Bitte berichten sie Fehler und fragen nach neuen Features auf ');
define('TOS', 'Nutzungsbedingungen');
define('PRIVACY', 'Datenschutz-Bestimmungen');
define('API', 'API (Entwicklertools)');
define('HOME', 'Startseite');
define('BASICFILEUPLOAD', 'Einfacher Datei Upload');
define('NAME', 'Name');
define('CONTENTS', 'Inhalt');
define('EXAMPLE', 'Beispiel');
define('CHUNKEDFILEUPLOAD', 'Aufgeteilter Datei Upload');
define('CHUNKEXPLANATION', 'Chunks werden in Chunks von bis zu 2 MB (<span class="code">2097152</span> bytes) aufgeteilt. Wiederholen Sie Folgendes für jeden Chunk');
define('FILE', 'Datei');
define('CHUNKCOUNT', 'Chunk Anzahl');
define('CHUNKNUMBER', 'Chunk Nummer');
define('CHUNKUSAGE', 'Der zuletzt hochgeladene Chunk gibt die Datei-ID wieder. Verwenden Sie es so');