<?php
define('LANGUAGE', 'en');
define('SLOGAN', 'File hosting done simple');
define('DESCRIPTION', 'File hosting done simple. Accountless file hosting with no limits. Share files easily for free on Starfiles.');
define('SELECTFILE', 'Select File');
define('UPLOADMULTIPLEFILES', 'Drop Files or Click Here');
define('UPLOADSINGLEFILE', 'Drop File or Click Here');
define('UPLOADFILE', 'Upload File');
define('UPLOADFILES', 'Upload Files');
define('JAVASCRIPTWARNING', 'Javascript is not enabled. Please enable it to enable all features.');
define('VPNWARNING', 'We have detected a VPN. Using a VPN may break some features.');
define('GOTOUPLOADPAGE', 'Go to Upload Page');
define('RECENTS', 'Your Recents');
define('ERRORS', 'Errors');
define('NOFILEUPLOADED', 'No File Uploaded');
define('FILETOOLARGE', 'File Too Large');
define('SERVERERROR', 'Server Error');
define('PARTIALLYUPLOADED', 'Partially Uploaded');
define('SYNCPROFILES', 'Sync Profiles');
define('FOOTERDESCRIPTION', 'Starfiles is a free file hosting service that allows users to store files and share them easily.');
define('HELPTEXT', 'Please report any issues and make feature requests via ');
define('TOS', 'Terms of Service');
define('PRIVACY', 'Privacy Policy');
define('API', 'API (Developer Tools)');
define('MADEBY', 'Made by');
define('JSHELPANDQUEUE', 'Javascript Improvement & Queueing System');
define('DESIGNERS', 'Designers');
define('HOME', 'Home');
define('BASICFILEUPLOAD', 'Basic File Upload');
define('NAME', 'Name');
define('CONTENTS', 'Contents');
define('EXAMPLE', 'Example');
define('CHUNKEDFILEUPLOAD', 'Chunked File Upload');
define('CHUNKEXPLANATION', 'Chunks are split into chunks of up to 2MB (<span class="code">2097152</span> bytes). Repeat the following for each chunk');
define('FILE', 'file');
define('CHUNKCOUNT', 'chunk count');
define('CHUNKNUMBER', 'chunk number');
define('CHUNKUSAGE', 'The last chunk uploaded will return the file ID. Use it like so');
define('FILENOTFOUND', 'File Not Found');
define('FILEDELETED', 'File Deleted');
define('PASSWORD', 'Password');
define('PASSWORDPROTECTED', 'Password Protected');
define('PASSWORDINCORRECT', 'Password Incorrect');
define('ENTERPASSWORD', 'Enter a password');
define('LOGIN', 'Login');
define('DIRECTURL', 'Direct URL');
define('DOWNLOAD', 'Download');
define('DOWNLOADS', 'Downloads');
define('DELETE', 'Delete');
define('REMOVEFROMPROFILE', 'Remove From Profile');
define('REPORT', 'Report File');
define('SAVE', 'Save');