<?php
define('LANGUAGE', 'es');
define('SLOGAN', 'Hosting de archivos hecho simple');
define('UPLOADMULTIPLEFILES', 'Suelte archivo o click aquí');
define('UPLOADSINGLEFILE', 'Suelte archivo o click aquí');
define('JAVASCRIPTWARNING', 'Javascript no está activado. Por favor actívelo para acceder a todas las características.');
define('VPNWARNING', 'Hemos detectado una VPN. Usar una VPN podría hacer mal funcionar algunas opciones.');
define('RECENTS', 'Recientes');
define('ERRORS', 'Errores');
define('UPLOADFAILED', 'Publicación Fallida');
define('NOFILEUPLOADED', 'Ningún archivo subido');
define('FILETOOLARGE', 'Archivo demasiado grande');
define('SERVERERROR', 'Error de Servidor');
define('PARTIALLYUPLOADED', 'Subido Parcialmente');
define('UPLOADCANCELLED', 'Subida Cancelada');
define('FOOTERDESCRIPTION', 'Starfiles es un servicio de hosting de archivos gratuitos que permite a los usuarios almacenar archivos y compartirlos fácilmente.');
define('HELPTEXT', 'Favor de reportar cualquier error y dejar recomendaciones en ');
define('TOS', 'Términos de Servicio');
define('PRIVACY', 'Política de Privacidad');
define('API', 'API (Herramientas del Desarrollador)');
define('HOME', 'Hogar');
define('BASICFILEUPLOAD', 'Subida de Archivos Básica');
define('CHUNKEDFILEUPLOAD', 'Subida de archivos fragmentados');
define('NAME', 'Nombre');
define('CONTENTS', 'Contenidos');
define('EXAMPLE', 'Ejemplo');
define('CHUNKEXPLANATION', 'Los fragmentos se dividen partes de 2MB (<span class="code">2097152</span> bytes). Repita lo siguiente para cada fragmento');
define('FILE', 'Archivo');
define('CHUNKCOUNT', 'Número de Fragmentos');
define('CHUNKNUMBER', 'Número de Fragmentos');
define('CHUNKUSAGE', 'El último fragmento subido devolverá un ID del archivo. Úselo así');