<?php
define('LANGUAGE', 'fr');
define('SLOGAN', 'L\'hébergement de fichiers fait simplement');
define('DESCRIPTION', 'Hébergement de fichiers simple. Hébergement de fichiers sans compte sans limites. Partagez des fichiers facilement et gratuitement sur Starfiles.');
define('SELECTFILE', 'Sélectionner un fichier');
define('UPLOADMULTIPLEFILES', 'Glissez le fichier ici ou cliquez pour le rechercher et l\'envoyer.');
define('UPLOADSINGLEFILE', 'Glizzer un ficher ici ou cliquez pour le rechercher et l\'envoyer');
// define('UPLOADFILE', 'Upload File');
// define('UPLOADFILES', 'Upload Files');
define('JAVASCRIPTWARNING', 'Javascript n\'est pas activé. Activez-le pour activer toutes les fonctionnalités.');
define('VPNWARNING', 'Nous avons détecté que vous utilisez un VPN. Utiliser ce genre d\'outil peut désactiver certaines fonctionnalités.');
// define('GOTOUPLOADPAGE', 'Go to Upload Page');
define('RECENTS', 'Fichiers Récents');
define('ERRORS', 'Erreurs');
define('NOFILEUPLOADED', 'Pas de fichier envoyé.');
define('FILETOOLARGE', 'Ichier trop volumineux');
define('SERVERERROR', 'Erreur du service, merci de réessayer ultérieurement');
define('PARTIALLYUPLOADED', 'Partiellement téléchargé');
// define('SYNCPROFILES', 'Sync Profiles');
define('FOOTERDESCRIPTION', 'Starfiles est un service d\'hébergement de fichiers qui vous autorise à envoyer des fichiers et les partager facilement.');
define('HELPTEXT', 'Merci de reporter tous les problèmes que vous encontrez et de proposer des fonctionnalités via ');
define('TOS', 'Conditions d\'utilisation');
define('PRIVACY', 'Politique de confidentialité');
define('API', 'API (Outils pour les développeurs)');
// define('MADEBY', 'Made by');
// define('JSHELPANDQUEUE', 'Javascript Improvement & Queueing System');
// define('DESIGNERS', 'Designers');
// define('HOME', 'Home');
define('BASICFILEUPLOAD', 'Envoi de fichier basique');
define('NAME', 'Nom');
define('CONTENTS', 'Contenus');
define('EXAMPLE', 'Exemple');
define('CHUNKEDFILEUPLOAD', 'Envoi de fichier par morceaux');
define('CHUNKEXPLANATION', 'Les morceaux sont découpés en morceaux jusqu\'a 2MB (<span class="code">2097152</span> bytes). Répétez le même processus pour chaque morceau.');
define('FILE', 'Fichier');
define('CHUNKCOUNT', 'nombre de morceaux');
define('CHUNKNUMBER', 'numéro des morceaux');
define('CHUNKUSAGE', 'Le dernier morceau envoyé va générer l\'ID du fichier. Utilisez le comme ça');
// define('FILENOTFOUND', 'File Not Found');
// define('FILEDELETED', 'File Deleted');
// define('PASSWORD', 'Password');
// define('PASSWORDPROTECTED', 'Password Protected');
// define('PASSWORDINCORRECT', 'Password Incorrect');
// define('ENTERPASSWORD', 'Enter a password');
// define('LOGIN', 'Login');
// define('DIRECTURL', 'Direct URL');
// define('DOWNLOAD', 'Download');
// define('DOWNLOADS', 'Downloads');
// define('DELETE', 'Delete');
// define('REMOVEFROMPROFILE', 'Remove From Profile');
// define('REPORT', 'Report File');
// define('SAVE', 'Save');