<?php
define('LANGUAGE', 'it');
define('SLOGAN', 'Hosting dei file fatto semplice');
define('UPLOADMULTIPLEFILES', 'Trascina file o clicca qui');
define('UPLOADSINGLEFILE', 'Trascina file o clicca qui');
define('JAVASCRIPTWARNING', 'Javascript non è abilitato. Per cortesia abilitatelo per abilitare tutte le funzioni.');
define('VPNWARNING', 'Noi abbiamo rilevato una VPN. Usare una VPN potrebbe far malfunzionamento qualche funzione.');
define('RECENTS', 'I tuoi recenti');
define('ERRORS', 'Errori');
define('UPLOADFAILED', 'Caricamento Fallito');
define('NOFILEUPLOADED', 'Nessun File è Stato Caricato');
define('FILETOOLARGE', 'File Troppo Grande');
define('SERVERERROR', 'Errore del Server');
define('PARTIALLYUPLOADED', 'Caricato in Parte');
define('UPLOADCANCELLED', 'Caricamento Annullato');
define('FOOTERDESCRIPTION', 'Starfiles  è un servizio di file hosting che consente ai utenti di immagazzinare file e condividerli facilmente.');
define('HELPTEXT', 'Se incontrate problemi o suggerire delle nuove funzioni scrivete al mio ');
define('TOS', 'Termini e Servizi');
define('PRIVACY', 'Politica Sulla Privacy ');
define('API', 'API (Risorse per Sviluppatori)');
define('HOME', 'Home');
define('BASICFILEUPLOAD', 'Caricato di File Normale');
define('NAME', 'Nome');
define('CONTENTS', 'Contenuti');
define('EXAMPLE', 'Esempi');
define('CHUNKEDFILEUPLOAD', 'Caricato frammentato dei file');
define('CHUNKEXPLANATION', 'I frammenti sono divisi in frammenti fino a 2MB (<span class="code">2097152</span> bytes) ripetere per ogni frammento');
define('FILE', 'file');
define('CHUNKCOUNT', 'Caricato Frammentato dei File');
define('CHUNKNUMBER', 'Frammenti Numero');
define('CHUNKUSAGE', 'L’ultimo frammento caricato ritornerà l’ID del file usatelo così');